---
sudo: false
language: ruby
cache: bundler
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.6
    dist: trusty
    env: BEAKER_debug=true BEAKER_set=docker-ubuntu-1204-x64
    script: bundle exec rake beaker
    services: docker
    sudo: required
notifications:
  email: false

